### PR TITLE
feat(tests/funcs/func_tonedetect): initial tests

### PR DESCRIPTION
**Pull request by gibbz00**
Pertains to: https://github.com/asterisk/asterisk/pull/814

### CODE REVIEW

**Comment by gibbz00** [comment]
cherry-pick-to: none

**Review by jcolp — APPROVED** [review]

**Comment by jcolp** [comment]
This should be a single commit with only the test changes, no merging of the base branch.

**Review by gtjoseph — CHANGES_REQUESTED** [review]
You have to remove the "Merge" commit.

**Comment by gibbz00** [comment]
Done!

**Review by jcolp — APPROVED** [review]

**Review by gtjoseph — APPROVED** [review]

**Comment by gibbz00** [comment]
Upstream PR has been merged. Merge this one too?

**Comment by gtjoseph** [comment]
> Upstream PR has been merged. Merge this one too?

Yeah sorry.  Lost track of this one.

**Pull request merged**
